version: '3.3'
services:
    broker :
        image : eclipse-mosquitto
        hostname : broker
        container_name : broker
        expose :
            - "1883"
        ports :
            - 6500:1883
        volumes :
            - /home/rajesh/Desktop/Edge/220340126023/Que5/mosquitto.conf
    publisherexam :
        build : .
        container_name : publisher
        hostname : pub
        depends_on :
            - broker